### PR TITLE
Update of the version of Delphes/DelphesMa5tune + compatibility with …

### PR DESCRIPTION
**Pull request by BFuks**
…M1 chips and Mac OS 13.0.
  
**Context:**

**Description of the Change:**
Update Delphes to version 3.5 as well as the patch for DelphesMA5tune, so that it is now compatible with M1 chips and Mac OS 13.0.

**Benefits:**
Restore compatibility with Delphes and DelphesMA5tune with new Apple computers

**Possible Drawbacks:**
No check made on Mac OS 13.1.

**Related GitHub Issues:**
[173](https://github.com/orgs/MadAnalysis/discussions/173)

### CODE REVIEW

**Comment by jackaraz** [comment]
Thanks @BenjaminFuks; I don't see any difference in ROOT installation. It still downloads the same root and is not able to compile it.

**Review by jackaraz — APPROVED** [review]
I cannot test it since it does not work on my system. However, I'm sure it will resolve the exroot error messages.

**Comment by BFuks** [comment]
Root must be installed locally. Then it works a least for me.

**Comment by jackaraz** [comment]
I'm noting that for MacOS v13.1, there is still an issue with root installation. This is because there is no specific 13.1 compatible root installation available. 

**Note for the users: please install the proper ROOT version for your particular OS version from [this link](https://root.cern/releases/release-62610/).**

**Pull request merged**
